address: munin.local:7890
channels:
  1: !!python/tuple [0, 64]
  2: !!python/tuple [64, 128]
  3: !!python/tuple [128, 192]
  4: !!python/tuple [192, 256]
  5: !!python/tuple [256, 320]
  6: !!python/tuple [320, 384]
  7: !!python/tuple [384, 448]
  8: !!python/tuple [448, 512]